services:
  - type: web
    name: love-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT game.app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 